### ISSUE TITLE
completion suggester support with mongoosastic

### ISSUE THREAD

**Issue by basiclaser** [mongoosastic/mongoosastic#182]
Hi there, I'm building a suggester feature. 
How can I index fields with a suggest field in mongoosastic?
Am I doing it wrong or does the feature just not exist?
Here was my code attempt: 
```
    title: {
      type: String,
      required: true,
      es_indexed: true,
      es_suggest: {
          type: "completion",
          search_analyzer: "simple",
          payloads: true
      }
    },
```
I received the error `[mapper_parsing_exception] Mapping definition for [title] has unsupported parameters:  [suggest `

**Comment by basiclaser** [comment]
ah, I managed to get suggestions working with the following syntax, now requesting a 'suggest' on title.suggested works. The issue was the superfluous `es_type: 'multi_field',` that i included on the title field, which is now removed:
```
    title: {
      type: String,
      required: true,
      es_indexed: true,
      es_fields: {
        suggested: { type: 'completion', analyzer: 'simple', payloads: true },
        not_analyzed: { type: 'string', index: 'not_analyzed' }
      }
    },
```

**Comment by gsccheng** [comment]
I'm having trouble with setting up the completion suggestions as well, but is this using an older Mongoosastic version with a different API? I don't see any relevant changes from the changelog since around the time of your post though. If I tried your particular case, the `suggest` field would not show up in the mappings at all; did you also have something like
```
suggest: {
  input: [{
         type: String,
         es_type: 'completion',
         es_analyzer: 'simple',
         es_search_analyzer: 'simple',
         es_indexed: true
      }]
}
```
where you explicitly list the `suggest` field for your schema?
