### ISSUE TITLE
Indexing on demand on populated fields not working

### ISSUE THREAD

**Issue by jagdish-176** [mongoosastic/mongoosastic#209]
Indexing on demand not working if use populate option in plugin.

doc.index(function(err){
  console.log(err);//gives error
})
It gives me error
[mapper_parsing_exception] object mapping for [favourites.companies] tried to parse field [null] as object, but found a concrete value.

**Comment by matt-zangen** [comment]
This is a bit old, but for those who need it, I worked around this by forcing default: null in my Mongoose model for the offending object.

You could also do this in the document you're indexing on demand if a default null is detrimental to your schema, but it seems riskier to rely on convention over configuration to index properly.

The failure in mongoosastic stems from a faul somewhere in the mongoosastic serializer module's _serializeObject function, perhaps deeper into the mapping-generator module. That's as far as I looked into it. The serialized object has all null object properties in the mapping serialized as empty objects instead of leaving them null.
