### ISSUE TITLE
Array of references don't work.

### ISSUE THREAD

**Issue by davidwu226** [mongoosastic/mongoosastic#213]
The following fails:

```
    var Book = new Schema({
        title: String
    });

    var Author = new Schema({
        name: {type:String}
        , books: [{type: Schema.Types.ObjectId, ref: 'Book',
                     es_schema: Book, es_type:'nested', es_include_in_parent:true}]
    })
    Author.plugin(mongoosastic);
```

The error returned is:

```
/app/node_modules/mongoosastic/lib/mapping-generator.js:50
    mapping[field].type = value.type;
                               ^

TypeError: Cannot read property 'type' of null
    at getMapping (/app/node_modules/mongoosastic/lib/mapping-generator.js:50:32)
    at getMapping (/app/node_modules/mongoosastic/lib/mapping-generator.js:62:35)
    at getMapping (/app/node_modules/mongoosastic/lib/mapping-generator.js:62:35)
    at getMapping (/app/node_modules/mongoosastic/lib/mapping-generator.js:62:35)
    at getMapping (/app/node_modules/mongoosastic/lib/mapping-generator.js:69:37)
    at Generator.generateMapping (/app/node_modules/mongoosastic/lib/mapping-generator.js:254:13)
    at getMapping (/app/node_modules/mongoosastic/lib/mongoosastic.js:19:13)
    at Mongoosastic (/app/node_modules/mongoosastic/lib/mongoosastic.js:172:15)

```

**Comment by TD-Stanley** [comment]
Shot in the dark, but do you need to include this in your Author.plugin :  
 populate: [
     {path: 'books'},
   ]

?

Having a difficult time getting a populate to work with this, also.

**Comment by isayme** [comment]
@guumaster this issue should closed refer https://github.com/mongoosastic/mongoosastic/commit/9719333dc5eb345611c9c52db4f3678c4f4de4dd

**Comment by markusv** [comment]
Yes this seems to work now. However the mapping created for array of references fails. I need to call createMapping because I need to index a geo point. This is the error message in the callback to createMapping

response: '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The [string] type is removed in 5.0 and automatic upgrade failed because parameters [select] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [pter]"}],"type":"illegal_argument_exception","reason":"The [string] type is removed in 5.0 and automatic upgrade failed because parameters [select] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [pter]"},"status":400}',

This is the mapping generated for the actual field:

"pter":{"type":"string","select":"name"}

The field in my mongoose model:

```
pter: [{
    type: mongoose.Schema.ObjectId,
    ref: 'pt',
    es_schema: ptSchema,
    es_indexed: true,
    es_select: 'name'
  }],
```

I also do the populate:

```
  populate: [
    { path: 'pter', select : 'name' }
  ]
```

What am i doing wrong?

Regards,
Markus
