### ISSUE TITLE
Synchronize not removing data from elasticsearch?

### ISSUE THREAD

**Issue by charliedavison** [mongoosastic/mongoosastic#251]
I'm just getting started with this plugin and all seems to be working well so far in terms of adding my documents into ES with the synchronize method, however the sync only seems to add documents and not remove them from ES when they are deleted from MongoDB.

I read through the docs but couldn't find any mention of whether this is the correct behavior. Is this intentional or am I missing an option somewhere?

**Comment by tsturzl** [comment]
I believe this is correct, a sync will not remove documents. Simply because it would mean iterating the entire ES dataset after syncing from mongodb, and then making sure each ES document exists in mongodb, which would add a significant amount of time to sync your index with your DB. Really you should only use sync to initially move your DB data into ES. Then if you plan to remove data you should attempt to do so through your app, otherwise you may need to completely resync your collection. This is how most sync methods work(mongo-connector, mongo-river, etc). So if you plan to migrate your data, remove data, or perform other administrative actions you typically need to drop your index and recreate it.

**Comment by charliedavison** [comment]
Thanks for the response.

That's not an issue then. I just wanted to clarify as my first instinct was that perhaps I was missing something!
