### ISSUE TITLE
Reindex Mongoose references in Elasticsearch

### ISSUE THREAD

**Issue by dropocol** [mongoosastic/mongoosastic#394]
I have a mongodb database in which I store my documents using mongoose. The sample schema is below.  

```
var userSchema = Schema({   
firstName :{type:  String , es_indexed:true},   
lastName  :{type:  String , es_indexed:true},   
friends  :[{type: String , ref: 'User', es_indexed:true , es_schema: userSchema}]}  
```
The friends array contains the friends Id's  from mongodb.  

My problem is mentioned below  

Let's say User-A is stored as a friend in User-B. User-A updates his  firstName and save it. Now when I search for User-A in Elasticsearch, I  get the latest version of the document.   

Now if I try to access the User-B in which User-A is listed as a  friend, I get the older version of the document. No matter how many  times I update, Elasticsearch doesn't give me the updated document in  the friends array but will give me a new one if I access it directly.  

I am fairly new to Elasticsearch so please guide me in the right  direction. I have spent last 2 days trying to figure out on my own but I  failed so any help would be much appreciated.

**Comment by BigFax** [comment]
It's an old issue, but I have the same question.

Let's take the example [in the doc](https://github.com/mongoosastic/mongoosastic/blob/master/docs/README.md#indexing-mongoose-references). It would be indexed in elasticsearch with this structure :

```json
"_source" : {
  "name" : "user's name here",
  "comments" : {
    "title" : "comment's title",
    "body": "the body of the comment"
  }
}
```

Unlike [mongoose-elasticsearch-xp](https://github.com/jbdemonte/mongoose-elasticsearch-xp#indexing-populated-models) which would only have one ObjectId field `"comments": 5b8f54c2c6d5624930480e0b`, mongoosastic will automatically populate referenced models for us with the data. Instead of being a reference, it becomes an embedded document.

Based on this, **what is the good way to update all users affected by the change of one comment with this mongoosastic module ?**

Indeed, if I update one comment which is referenced in 1000 users, the 1000 users will keep the old version of the comment (even if I use `{ new: true }` as explain in the doc). The comment itself will be updated, but I should update the 1000 users to update each reference of them in ElasticSearch. I checked the source code and it looks like it is expected because indexing is triggered only when we use some middleware like `save`, `findOneAndUpdate`, `remove`... on the parent (here `User`). We could also use `synchronize` method. I think if it is a reference, it should be not embedded in ElasticSearch and stick to his parent as it is. What do people think about it ?
