### ISSUE TITLE
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (null)

### ISSUE THREAD

**Issue by SaeedSheikhi** [mongoosastic/mongoosastic#489]
## Your Environments
- mongoosastic version: 4.5.0
- node version: 12.2.0
- mongoose version: 5.6.4
- elasticsearch version: 7.x

## Expected Behavior

what should we do to get more info from error? e.g which model or docs are throwing error or something like that.
## Actual Behavior

crash the app on production env
## Error Stack

```shell
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (null)
at EventEmitter.emit (events.js:185:17)
at node_modules/mongoosastic/lib/mongoosastic.js:734:23
at respond (node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:336:9)
at checkRespForFailure (node_modules/mongoosastic/node_modules/elasticsearch/src/lib/transport.js:274:7)
at HttpConnector.<anonymous> (node_modules/mongoosastic/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
at IncomingMessage.wrapper (node_modules/lodash/lodash.js:4935:19)
at IncomingMessage.emit (events.js:201:15)
at endReadableNT (_stream_readable.js:1130:12)
t processTicksAndRejections (internal/process/task_queues.js:84:9) {
context: null
 }
```

**Comment by sugandhigopi** [comment]
same here

**Comment by jewanisw** [comment]
Same for me. Happening with synchronize or createMapping, not sure what yet. Node 10.6.0, mongoosastic 4.5.0, mongoose 5.6.10, elasticsearch version 6.x

**Comment by foxinni** [comment]
Any idea about this? Also getting it.

**Comment by SaeedSheikhi** [comment]
@foxinni  Yeah, last week I investigate the source code, replace `bulkErrEm.emit('error', null, info.index)` with `bulkErrEm.emit('error', null, info)` will show the actual error. 

if that doesn't, work put `console.log(info)` before this line
https://github.com/mongoosastic/mongoosastic/blob/1ba9fc864fc61d973021e51a3baeafcee93427e6/lib/mongoosastic.js#L725 
it probably works. the main issue is relative to your main docs, maybe _id references in mongodb.

**Comment by foxinni** [comment]
![image](https://user-images.githubusercontent.com/124101/66228334-72d26f80-e6df-11e9-948b-1826a3ccf37b.png)

Console-ing `info` helped. I can see now what the issue was.

`curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'` solved it for me.

**Comment by SaeedSheikhi** [comment]
Cheers @yoitsro, 
I can't reproduce issue to test the PR :D, did the first solution work? 

> replace `bulkErrEm.emit('error', null, info.index)` with `bulkErrEm.emit('error', null, info)` will show the actual error.

**Comment by foxinni** [comment]
Not sure. The root problem was the read_only mode. Ping me again if you don't get to reproduce.

**Comment by ddtraceweb** [comment]
i have same error.

**Comment by zhfahan77** [comment]
I am having the same error

### Environment
- node version: 10.17.0
- elasticsearch : 16.3.0
- mongoosastic : 4.5.0
- mongoose: 5.5.6

**I am running Elastic Search in Docker.**

When I printer the error object like @foxinni i have found same error details

`{ type: 'cluster_block_exception',
  reason:
   'index [products] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];' }`

![image](https://user-images.githubusercontent.com/18385348/71797965-7d9ff600-307a-11ea-931a-d079690ea6a4.png)

I immediately searched the problem and found [this](https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282/7). This is due to elastic search makes the disk as read only when it reaches certain disk size and no space to write more. This is may be a precaution type step taken by the elastic guys. [Helpful](https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html).

Thus, I removed docker volume of the elastic search, and it was back to normal again. So the fix would be to update elastic search settings as below,

```
Method: PUT
URL: <elastic_search_server_url>/<index_name>/_settings
body:
```

```
{
 "index": {
   "blocks": {
     "read_only_allow_delete": "false"
    }
  }
}
```

**Comment by thanhdat21293** [comment]
Same for me.
After that, I seem it conflic between mongoosastic with elasticsearch.

I removed code the below and it working.
```
// let stream = User.synchronize();
//let count = 0;

//stream.on('data', function(err, doc){
//	count++;
//	console.log(count);
//});
// stream.on('close', function(){
// 	console.log('indexed all User documents!');
// });
// stream.on('error', function(err){
// 	console.log(err);
// });
```

**Comment by uramen** [comment]
`User.synchronize()` tries to insert existing indexes from MongoDB via existing mapping. It seems that we need to clear the mapping and create a fresh one. But the question is how?

> Same for me.
> After that, I seen it conflict between mongoosastic with elasticsearch.
> 
> I removed code the below and it working.
> 
> ```
> let stream = User.synchronize();
> let count = 0;
> 
> stream.on('data', function(err, doc){
> 	count++;
> 	console.log(count);
> });
> stream.on('close', function(){
> 	console.log('indexed all User documents!');
> });
> stream.on('error', function(err){
> 	console.log(err);
> });
> ```

**Comment by SaeedSheikhi** [comment]
@uramen [Removing data from elasticsearch](https://stackoverflow.com/questions/22924300/removing-data-from-elasticsearch)

**Comment by zhfahan77** [comment]
However, it would be better if we can update only the diff, removing everything and re indexing might create congestion if data set is huge.
